import '@app/globals.css';
import NavigationBar from '@/shared/components/NavigationBar';
import RouteGuard from '@/shared/components/RouteGuard';

import type { Metadata } from 'next';
import { ReduxProvider } from '@/store/ReduxProvider';
import { NextIntlClientProvider } from 'next-intl';
import { ReactNode } from 'react';
import { routing } from 'i18n/routing';
import 'primereact/resources/themes/lara-light-blue/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import type { Locale } from 'i18n/routing';
import { getMessages, setRequestLocale } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { ToastProvider } from '@/shared/providers';
import { montserrat } from '@app/fonts';

import AuthProvider from '@/lib/auth/AuthProvider';

import { StatusConfigProvider } from '@/lib/contexts/StatusConfigContext';



export const metadata: Metadata = {
  title: 'WFZO - World Free Zones Organization',
  description: 'Generated by DigitalWorks',
  icons: {
    shortcut: [
      {
        url: '/favicon.ico',
        type: 'image/x-icon',
        sizes: '16x16',
      },
    ],
    apple: [
      {
        url: '/wfzologo.png',
        type: 'image/png',
        sizes: '180x180',
      },
    ],
  },
};
type Props = {
  children: ReactNode;
  params: Promise<{ locale: string }>;
};
export default async function DashboardLayout({ children, params }: Props) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }

  setRequestLocale(locale);

  const messages = await getMessages({ locale });
  return (
    <html lang={locale}>
       <body className={`${montserrat.className} bg-[#FCFAF8]`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <AuthProvider>
            <ReduxProvider>
              <RouteGuard isProtected={true} />
              <ToastProvider />
              <StatusConfigProvider>
                <NavigationBar />
                {children}
                
              </StatusConfigProvider>
            </ReduxProvider>
          </AuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
