export enum ErrorCode {
  VALIDATION = "ERR_VALIDATION",
  VALIDATION_FIELD = "ERR_VALIDATION_FIELD",
  NOT_FOUND = "ERR_NOT_FOUND",
  CONFLICT = "ERR_CONFLICT",
  FORBIDDEN = "ERR_FORBIDDEN",
  UNAUTHORIZED = "ERR_UNAUTHORIZED",
  INTERNAL = "ERR_INTERNAL",
}
