import '@app/globals.css';
import type { Metadata } from 'next';
import { ReduxProvider } from '@/store/ReduxProvider';
import { NextIntlClientProvider } from 'next-intl';
import { ReactNode } from 'react';
import { routing } from 'i18n/routing';
import 'primereact/resources/themes/lara-light-blue/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import type { Locale } from 'i18n/routing';
import { getMessages, setRequestLocale } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { ToastProvider } from '@/shared/providers';
import { montserrat } from '@app/fonts';
import ContactFooterSection from '@/features/layout/components/FooterSection';
import NavigationSection from '@/features/layout/components/NavigationSection';
import AuthProvider from '@/lib/auth/AuthProvider';
import GoogleAnalytics from '@/shared/components/GoogleAnalytics';
import { MembershipProvider } from '@/lib/membership/MembershipProvider';
import { getGuestFeatures } from '@/services/membershipService';


export const metadata: Metadata = {
  title: 'WFZO - World Free Zones Organization',
  description: 'Generated by DigitalWorks',
  icons: {
    shortcut: [
      {
        url: '/favicon.ico',
        type: 'image/x-icon',
        sizes: '16x16',
      },
    ],
    apple: [
      {
        url: '/wfzologo.png',
        type: 'image/png',
        sizes: '180x180',
      },
    ],
  },
};
type Props = {
  children: ReactNode;
  params: Promise<{ locale: string }>;
};
export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }

  setRequestLocale(locale);

  const messages = await getMessages({ locale });
  
  // Fetch guest features for initial load (cached)
  let guestFeatures = undefined;
  try {
    guestFeatures = await getGuestFeatures();
  } catch (error) {
    console.error('Failed to fetch guest features:', error);
  }
  
  return (
    <html lang={locale}>
       <body className={`${montserrat.className} bg-[#FCFAF8]`}>
        <GoogleAnalytics />
        <NextIntlClientProvider locale={locale} messages={messages}>
          <AuthProvider>
            <MembershipProvider initialFeatures={guestFeatures}>
              <ReduxProvider>
                <ToastProvider />
                <NavigationSection params={{ locale }}/>
                {children}
                <ContactFooterSection params={{ locale }} />
              </ReduxProvider>
            </MembershipProvider>
          </AuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
